// Generated by CoffeeScript 1.9.2
(function() {
  var SitePlanScreen,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  SitePlanScreen = (function() {
    function SitePlanScreen(image) {
      this.relayout = bind(this.relayout, this);
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createScrollView({
        maxZoomScale: 2.0
      });
      this.backgroundImage = Ti.UI.createImageView({
        image: image.file_name,
        width: image.width,
        height: image.height,
        left: 0,
        top: 0
      });
      this.view.add(this.backgroundImage);
    }

    SitePlanScreen.prototype.init = function() {
      return this;
    };

    SitePlanScreen.prototype.play = function() {};

    SitePlanScreen.prototype.relayout = function() {};

    return SitePlanScreen;

  })();

  module.exports = SitePlanScreen;

}).call(this);
