// Generated by CoffeeScript 1.9.2
(function() {
  var ANIMATION_DURATION, MainMenuScreen, SCREEN_HEIGHT, SCREEN_WIDTH,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ANIMATION_DURATION = 200;

  SCREEN_WIDTH = 1024;

  SCREEN_HEIGHT = 768;

  MainMenuScreen = (function() {
    function MainMenuScreen() {
      this.play = bind(this.play, this);
      this.animateInHomeButton = bind(this.animateInHomeButton, this);
      this.animateInGalleryButton = bind(this.animateInGalleryButton, this);
      this.animateInFloorplanButton = bind(this.animateInFloorplanButton, this);
      this.animateInAboutButton = bind(this.animateInAboutButton, this);
      this.animateInLocationButton = bind(this.animateInLocationButton, this);
      this.animateOutHomeButton = bind(this.animateOutHomeButton, this);
      this.animateOutGalleryButton = bind(this.animateOutGalleryButton, this);
      this.animateOutFloorplanButton = bind(this.animateOutFloorplanButton, this);
      this.animateOutAboutButton = bind(this.animateOutAboutButton, this);
      this.animateOutLocationButton = bind(this.animateOutLocationButton, this);
      this.menuButtonClicked = bind(this.menuButtonClicked, this);
      this.init = bind(this.init, this);
      this.view = Ti.UI.createView();
      this.buttonHome = Ti.UI.createButton({
        backgroundImage: 'MainMenu-HomeButton.png',
        width: 412 / 2,
        height: 1536 / 2
      });
      this.view.add(this.buttonHome);
      this.buttonAbout = Ti.UI.createButton({
        backgroundImage: 'MainMenu-AboutButton.png',
        width: 406 / 2,
        height: 1536 / 2
      });
      this.view.add(this.buttonAbout);
      this.buttonLocation = Ti.UI.createButton({
        backgroundImage: 'MainMenu-LocationButton.png',
        width: 410 / 2,
        height: 1536 / 2
      });
      this.view.add(this.buttonLocation);
      this.buttonFloorplan = Ti.UI.createButton({
        backgroundImage: 'MainMenu-FloorplanButton.png',
        width: 412 / 2,
        height: 1536 / 2
      });
      this.view.add(this.buttonFloorplan);
      this.buttonGallery = Ti.UI.createButton({
        backgroundImage: 'MainMenu-GalleryButton.png',
        width: 408 / 2,
        height: 1536 / 2
      });
      this.view.add(this.buttonGallery);
      this.onButtonClicked = null;
    }

    MainMenuScreen.prototype.init = function() {
      this.buttonHome.left = 0;
      this.buttonHome.top = -this.buttonHome.height;
      this.buttonHome.addEventListener("click", this.menuButtonClicked);
      this.buttonHome.button_id = 0;
      this.buttonAbout.left = this.buttonHome.width + this.buttonHome.left;
      this.buttonAbout.top = this.buttonAbout.height + 1;
      this.buttonAbout.addEventListener("click", this.menuButtonClicked);
      this.buttonAbout.button_id = 1;
      this.buttonLocation.left = this.buttonAbout.width + this.buttonAbout.left;
      this.buttonLocation.top = -this.buttonLocation.height;
      this.buttonLocation.addEventListener("click", this.menuButtonClicked);
      this.buttonLocation.button_id = 2;
      this.buttonFloorplan.left = this.buttonLocation.width + this.buttonLocation.left;
      this.buttonFloorplan.top = this.buttonFloorplan.height + 1;
      this.buttonFloorplan.addEventListener("click", this.menuButtonClicked);
      this.buttonFloorplan.button_id = 3;
      this.buttonGallery.left = this.buttonFloorplan.width + this.buttonFloorplan.left;
      this.buttonGallery.top = this.buttonGallery.height + 1;
      this.buttonGallery.addEventListener("click", this.menuButtonClicked);
      this.buttonGallery.button_id = 4;
      return this;
    };

    MainMenuScreen.prototype.menuButtonClicked = function(e) {
      if (e.source.button_id !== 0) {
        this.animateOutHomeButton();
        return setTimeout((function(_this) {
          return function() {
            if (_this.onButtonClicked !== null) {
              return _this.onButtonClicked(e.source.button_id);
            }
          };
        })(this), ANIMATION_DURATION * 5);
      }
    };

    MainMenuScreen.prototype.animateOutLocationButton = function() {
      return this.buttonLocation.animate({
        top: this.buttonLocation.height + 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {};
      })(this));
    };

    MainMenuScreen.prototype.animateOutAboutButton = function() {
      return this.buttonAbout.animate({
        top: this.buttonAbout.height + 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateOutLocationButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateOutFloorplanButton = function() {
      return this.buttonFloorplan.animate({
        top: this.buttonFloorplan.height + 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateOutAboutButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateOutGalleryButton = function() {
      return this.buttonGallery.animate({
        top: this.buttonGallery.height + 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateOutFloorplanButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateOutHomeButton = function() {
      return this.buttonHome.animate({
        top: this.buttonHome.height + 1,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateOutGalleryButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateInLocationButton = function() {
      return this.buttonLocation.animate({
        top: 0,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {};
      })(this));
    };

    MainMenuScreen.prototype.animateInAboutButton = function() {
      return this.buttonAbout.animate({
        top: 0,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateInLocationButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateInFloorplanButton = function() {
      return this.buttonFloorplan.animate({
        top: 0,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateInAboutButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateInGalleryButton = function() {
      return this.buttonGallery.animate({
        top: 0,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateInFloorplanButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.animateInHomeButton = function() {
      return this.buttonHome.animate({
        top: 0,
        duration: ANIMATION_DURATION
      }, (function(_this) {
        return function() {
          return _this.animateInGalleryButton();
        };
      })(this));
    };

    MainMenuScreen.prototype.play = function() {
      return this.animateInHomeButton();
    };

    return MainMenuScreen;

  })();

  module.exports = MainMenuScreen;

}).call(this);
