// Generated by CoffeeScript 1.9.2
(function() {
  var ApplicationWindow, FirstView, MainMenuScreen, ScreenWithBottomMenu,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  FirstView = require('ui/common/IntroScreen');

  MainMenuScreen = require("ui/common/MainMenuScreen");

  ScreenWithBottomMenu = require("ui/common/ScreenWithBottomMenu");

  ApplicationWindow = (function() {
    ApplicationWindow.prototype.showNormalScreenFlow = function(self) {
      var firstView;
      firstView = new FirstView();
      firstView.onExit = (function(_this) {
        return function() {
          var mainMenuScreen;
          mainMenuScreen = new MainMenuScreen().init();
          mainMenuScreen.onButtonClicked = function(button_id) {
            var topBarScreen;
            topBarScreen = new ScreenWithBottomMenu().init();
            topBarScreen.onDoubleTapped = function(eventInfo) {
              var eventData, fullscreenGallery;
              if (eventInfo.event_type === "GALLERY") {
                eventData = eventInfo.event_data;
                console.log(eventInfo);
                fullscreenGallery = new FullScreenGallery().init();
                fullscreenGallery.setEventData(eventData);
                self.add(fullscreenGallery);
                return fullscreenGallery.play();
              }
            };
            topBarScreen.onDayView = function(image) {};
            topBarScreen.logoButtonClicked = function() {
              mainMenuScreen.view.remove(topBarScreen.view);
              return mainMenuScreen.play();
            };
            mainMenuScreen.view.add(topBarScreen.view);
            topBarScreen.play();
            return topBarScreen.click(button_id);
          };
          self.add(mainMenuScreen);
          return mainMenuScreen.play();
        };
      })(this);
      self.add(firstView);
      firstView.play();
      return self;
    };

    ApplicationWindow.prototype.showEmergencyScreenFlow = function(self) {
      var mainMenuScreen;
      mainMenuScreen = new MainMenuScreen().init();
      self.add(mainMenuScreen);
      mainMenuScreen.play();
      return self;
    };

    function ApplicationWindow() {
      this.showEmergencyScreenFlow = bind(this.showEmergencyScreenFlow, this);
      this.showNormalScreenFlow = bind(this.showNormalScreenFlow, this);
      var self;
      self = Ti.UI.createWindow({
        backgroundColor: '#ede0c8',
        orientationModes: [Ti.UI.LANDSCAPE_LEFT, Ti.UI.LANDSCAPE_RIGHT],
        statusBarStyle: Titanium.UI.iPhone.StatusBar.LIGHT_CONTENT,
        fullscreen: true
      });
      return this.showNormalScreenFlow(self);
    }

    return ApplicationWindow;

  })();

  module.exports = ApplicationWindow;

}).call(this);
